package ar.gob.buenosaires.esb.exception;

public enum CodigoError {

	JURISDICCION_REPETIDA("301"), OBJETIVO_ESTRATEGICO_REPETIDO("302"), OBJETIVO_OPERATIVO_REPETIDO("303"),
	PROYECTO_REPETIDO("304"), ETIQUETA_REPETIDA("305"), TEMA_TRANSVERSAL_REPETIDO("306"), COMPROMISO_PUBLICO_REPETIDO("307"), PRESUPUESTO_APROBADO_ERRONEO("308"),
	PRIORIDAD_JEFATURA_INCOMPLETA("309"), USUARIO_DUPLICADO("310"), 
	PROYECTO_VALIDACION_1("311"), PROYECTO_VALIDACION_2("312"), PROYECTO_VALIDACION_3("313"), PROYECTO_VALIDACION_4("314"), PROYECTO_VALIDACION_5("315"),
	PROYECTO_VALIDACION_6("316"), PROYECTO_VALIDACION_7("317"),PROYECTO_VALIDACION_8("318"),PROYECTO_VALIDACION_9("319"),PROYECTO_VALIDACION_10("320"),
	ACCION_INEXISTENTE("404"), JURISDICCION_INEXISTENTE("405"), OBJETIVO_ESTRATEGICO_INEXISTENTE("406"), OBJETIVO_OPERATIVO_INEXISTENTE("407"), 
	PROYECTO_INEXISTENTE("408"), ETIQUETA_INEXISTENTE("409"), ROL_INEXISTENTE("410"), USUARIO_INEXISTENTE("411"), 
	COMPROMISO_PUBLICO_INEXISTENTE("412"), TEMA_TRANSVERSAL_INEXISTENTE("413"), OBRA_INEXISTENTE("414"), TIPO_OBRA_INEXISTENTE("415"), 
	PRESUPUESTO_POR_MES_INEXISTENTE("416"),	PROYECTO_NO_CANCELADO("429"), PROYECTO_NO_PRESENTADO_O_VERIFICADO("430"), 
	PROYECTO_NO_PRESENTADO("431"), PROYECTO_NO_COMPLETO("432"), ESTADO_INVALIDO("435"), USUARIO_INACTIVO("433"), PASS_INVALIDO("434"), ERROR_LECTURA_ARCHIVO_ADJUNTO("435"),
	TIMEOUT_BUS("504"), ERROR_PARSEO("554"), FALTA_USUARIO("505");

	private String codigo;

	CodigoError(String name) {
		this.codigo = name;
	}

	public String getCodigo() {
		return codigo;
	}

}
